add_test( [==[SanityCheck ensures values are safe]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[SanityCheck ensures values are safe]==]  )
set_tests_properties( [==[SanityCheck ensures values are safe]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[CrossoverLR4 splits and sums flat]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[CrossoverLR4 splits and sums flat]==]  )
set_tests_properties( [==[CrossoverLR4 splits and sums flat]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[ScopedDenormalFlush behavior]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[ScopedDenormalFlush behavior]==]  )
set_tests_properties( [==[ScopedDenormalFlush behavior]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[DC Blocker removes DC offset]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[DC Blocker removes DC offset]==]  )
set_tests_properties( [==[DC Blocker removes DC offset]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[CharacterOscillator FM Depth block processing]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[CharacterOscillator FM Depth block processing]==]  )
set_tests_properties( [==[CharacterOscillator FM Depth block processing]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[Anti-Click Ramp behavior]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[Anti-Click Ramp behavior]==]  )
set_tests_properties( [==[Anti-Click Ramp behavior]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[Saturator basic functionality]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[Saturator basic functionality]==]  )
set_tests_properties( [==[Saturator basic functionality]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[Smoother interpolates values]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[Smoother interpolates values]==]  )
set_tests_properties( [==[Smoother interpolates values]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[Wavefolder basic functionality]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[Wavefolder basic functionality]==]  )
set_tests_properties( [==[Wavefolder basic functionality]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[StateVariableFilter basic functionality]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[StateVariableFilter basic functionality]==]  )
set_tests_properties( [==[StateVariableFilter basic functionality]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[SubOscillator has deterministic phase]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[SubOscillator has deterministic phase]==]  )
set_tests_properties( [==[SubOscillator has deterministic phase]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
add_test( [==[Oversampler polyphase FIR structure works]==] /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests/dsp_tests [==[Oversampler polyphase FIR structure works]==]  )
set_tests_properties( [==[Oversampler polyphase FIR structure works]==] PROPERTIES WORKING_DIRECTORY /Users/grzzi/Desktop/dnb_bass_synth/build_p4_gate_check/tests SKIP_RETURN_CODE 4)
set( dsp_tests_TESTS [==[SanityCheck ensures values are safe]==] [==[CrossoverLR4 splits and sums flat]==] [==[ScopedDenormalFlush behavior]==] [==[DC Blocker removes DC offset]==] [==[CharacterOscillator FM Depth block processing]==] [==[Anti-Click Ramp behavior]==] [==[Saturator basic functionality]==] [==[Smoother interpolates values]==] [==[Wavefolder basic functionality]==] [==[StateVariableFilter basic functionality]==] [==[SubOscillator has deterministic phase]==] [==[Oversampler polyphase FIR structure works]==])
